### ISSUE TITLE
scrollbars

### ISSUE THREAD

**Issue by incantatem1** [Elhary/obsidian-Pale#2]
is it intentional that this theme has no scrollbars? that's pretty annoying when using a touchpad

**Comment by hariiy-sys** [comment]
Thank you for your feedback! Could you please specify which scrollbar you're referring to?

**Comment by incantatem1** [comment]
the editor scrollbar, it's apparently waaaaay out of the window on the right side of the screen since it seems the editor is infinite to the right side??

**Comment by incantatem1** [comment]
yay, scrollbars! i can use this nice theme easier now, thank you <3
